[package]
name = "chapter-11-2-controlling-how-tests-are-run"
version = "0.1.0"
authors = ["Luxurno Marcin Szostak <luxurno@luxurno.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
